package model.standard;

import java.util.Locale;

import model.LabeledColorInventory;

public abstract class RalClassic extends Standard {

	public RalClassic(Locale locale) {
		super(locale);
	}

	@Override
	public void fillInventory(LabeledColorInventory inventory) {

		this.addInInventory(inventory, "RAL 1000", 190, 189, 127, "Grünbeige", "Green beige", "Beige vert", "Beige verdoso", "Beige verdastro", "Groenbeige");
		this.addInInventory(inventory, "RAL 1001", 194, 176, 120, "Beige", "Beige", "Beige", "Beige", "Beige", "Beige");
		this.addInInventory(inventory, "RAL 1002", 198, 166, 100, "Sandgelb", "Sand yellow", "Jaune sable", "Amarillo arena", "Giallo sabbia", "Zandgeel");
		this.addInInventory(inventory, "RAL 1003", 229, 190, 1, "Signalgelb", "Signal yellow", "Jaune de sécurité", "Amarillo señales", "Giallo segnale", "Signaalgeel");
		this.addInInventory(inventory, "RAL 1004", 205, 164, 52, "Goldgelb", "Golden yellow", "Jaune or", "Amarillo oro", "Giallo oro", "Goudgeel");
		this.addInInventory(inventory, "RAL 1005", 169, 131, 7, "Honiggelb", "Honey yellow", "Jaune miel", "Amarillo miel", "Giallo miele", "Honinggeel");
		this.addInInventory(inventory, "RAL 1006", 228, 160, 16, "Maisgelb", "Maize yellow", "Jaune maïs", "Amarillo maiz", "Giallo polenta", "Maisgeel");
		this.addInInventory(inventory, "RAL 1007", 220, 156, 0, "Narzissengelb", "Daffodil yellow", "Jaune narcisse", "Amarillo narciso", "Giallo narciso", "Narcissengeel");
		this.addInInventory(inventory, "RAL 1011", 138, 102, 66, "Braunbeige", "Brown beige", "Beige brun", "Beige pardo", "Beige marrone", "Bruinbeige");
		this.addInInventory(inventory, "RAL 1012", 199, 180, 70, "Zitronengelb", "Lemon yellow", "Jaune citron", "Amarillo limón", "Giallo limone", "Citroengeel");
		this.addInInventory(inventory, "RAL 1013", 234, 230, 202, "Perlweiß", "Oyster white", "Blanc perlé", "Blanco perla", "Bianco perla", "Parelwit");
		this.addInInventory(inventory, "RAL 1014", 225, 204, 79, "Elfenbein", "Ivory", "Ivoire", "Marfil", "Avorio", "Ivoorkleurig");
		this.addInInventory(inventory, "RAL 1015", 230, 214, 144, "Hellelfenbein", "Light ivory", "Ivoire clair", "Marfil claro", "Avorio chiaro", "Licht ivoorkleurig");
		this.addInInventory(inventory, "RAL 1016", 237, 255, 33, "Schwefelgelb", "Sulfur yellow", "Jaune soufre", "Amarillo azufre", "Giallo zolfo", "Zwavelgeel");
		this.addInInventory(inventory, "RAL 1017", 245, 208, 51, "Safrangelb", "Saffron yellow", "Jaune safran", "Amarillo azafrán", "Giallo zafferano", "Saffraangeel");
		this.addInInventory(inventory, "RAL 1018", 248, 243, 53, "Zinkgelb", "Zinc yellow", "Jaune zinc", "Amarillo de zinc", "Giallo zinco", "Zinkgeel");
		this.addInInventory(inventory, "RAL 1019", 158, 151, 100, "Graubeige", "Grey beige", "Beige gris", "Beige agrisado", "Beige grigiastro", "Grijsbeige");
		this.addInInventory(inventory, "RAL 1020", 153, 153, 80, "Olivgelb", "Olive yellow", "Jaune olive", "Amarillo oliva", "Giallo olivastro", "Olijfgeel");
		this.addInInventory(inventory, "RAL 1021", 243, 218, 11, "Rapsgelb", "Rape yellow", "Jaune colza", "Amarillo colza", "Giallo navone", "Koolzaadgeel");
		this.addInInventory(inventory, "RAL 1023", 250, 210, 1, "Verkehrsgelb", "Traffic yellow", "Jaune signalisation", "Amarillo tráfico", "Giallo traffico", "Verkeersgeel");
		this.addInInventory(inventory, "RAL 1024", 174, 160, 75, "Ockergelb", "Ochre yellow", "Jaune ocre", "Amarillo ocre", "Giallo ocra", "Okergeel");
		this.addInInventory(inventory, "RAL 1026", 255, 255, 0, "Leuchtgelb", "Luminous yellow", "Jaune brillant", "Amarillo brillante", "Giallo brillante", "Briljantgeel");
		this.addInInventory(inventory, "RAL 1027", 157, 145, 1, "Currygelb", "Curry", "Jaune curry", "Amarillo curry", "Giallo curry", "Kerriegeel");
		this.addInInventory(inventory, "RAL 1028", 244, 169, 0, "Melonengelb", "Melon yellow", "Jaune melon", "Amarillo melón", "Giallo melone", "Meloengeel");
		this.addInInventory(inventory, "RAL 1032", 214, 174, 1, "Ginstergelb", "Broom yellow", "Jaune genêt", "Amarillo retama", "Giallo scopa", "Bremgeel");
		this.addInInventory(inventory, "RAL 1033", 243, 165, 5, "Dahliengelb", "Dahlia yellow", "Jaune dahlia", "Amarillo dalia", "Giallo dahlien", "Dahliageel");
		this.addInInventory(inventory, "RAL 1034", 239, 169, 74, "Pastellgelb", "Pastel yellow", "Jaune pastel", "Amarillo pastel", "Giallo pastello", "Pastelgeel");
		this.addInInventory(inventory, "RAL 1035", 106, 93, 77, "Perlbeige", "Pearl beige", "Beige nacré", "Beige perlado", "Beige perlato", "Parelmoergrijs");
		this.addInInventory(inventory, "RAL 1036", 112, 83, 53, "Perlgold", "Pearl gold", "Or nacré", "Oro perlado", "Oro perlato", "Parelmoergoud");
		this.addInInventory(inventory, "RAL 1037", 243, 159, 24, "Sonnengelb", "Sun yellow", "Jaune soleil", "Amarillo sol", "Giallo sole", "Zonnegeel");
		this.addInInventory(inventory, "RAL 2000", 237, 118, 14, "Gelborange", "Yellow orange", "Orangé jaune", "Amarillo naranja", "Arancio giallastro", "Geeloranje");
		this.addInInventory(inventory, "RAL 2001", 201, 60, 32, "Rotorange", "Red orange", "Orangé rouge", "Rojo anaranjado", "Arancio rossastro", "Roodoranje");
		this.addInInventory(inventory, "RAL 2002", 203, 40, 33, "Blutorange", "Vermilion", "Orangé sang", "Naranja sanguineo", "Arancio sanguigno", "Vermiljoen");
		this.addInInventory(inventory, "RAL 2003", 255, 117, 20, "Pastellorange", "Pastel orange", "Orangé pastel", "Naranja pálido", "Arancio pastello", "Pasteloranje");
		this.addInInventory(inventory, "RAL 2004", 244, 70, 17, "Reinorange", "Pure orange", "Orangé pur", "Naranja puro", "Arancio puro", "Zuiver oranje");
		this.addInInventory(inventory, "RAL 2005", 255, 35, 1, "Leuchtorange", "Luminous orange", "Orangé brillant", "Naranja brillante", "Arancio brillante", "Briljant oranje");
		this.addInInventory(inventory, "RAL 2007", 255, 164, 32, "Leuchthellorange", "Luminous bright orange", "Orangé clair brillant", "Naranja claro brillante", "Arancio chiaro brillante",
				"Briljant lichtoranje");
		this.addInInventory(inventory, "RAL 2008", 247, 94, 37, "Hellrotorange", "Bright red orange", "Orangé rouge clair", "Rojo claro anaranjado", "Rosso arancio chiaro", "Licht roodoranje");
		this.addInInventory(inventory, "RAL 2009", 245, 64, 33, "Verkehrsorange", "Traffic orange", "Orangé signalisation", "Naranja tráfico", "Arancio traffico", "Verkeersoranje");
		this.addInInventory(inventory, "RAL 2010", 216, 75, 32, "Signalorange", "Signal orange", "Orangé de sécurité", "Naranja señales", "Arancio segnale", "Signaaloranje");
		this.addInInventory(inventory, "RAL 2011", 236, 124, 38, "Tieforange", "Deep orange", "Orangé foncé", "Naranja intenso", "Arancio profondo", "Dieporanje");
		this.addInInventory(inventory, "RAL 2012", 235, 106, 14, "Lachsorange", "Salmon range", "Orangé saumon", "Naranja salmón", "Arancio salmone", "Zalmoranje");
		this.addInInventory(inventory, "RAL 2013", 195, 88, 49, "Perlorange", "Pearl orange", "Orangé nacré", "Naranja perlado", "Arancio perlato", "Parelmoeroranje");
		this.addInInventory(inventory, "RAL 3000", 175, 43, 30, "Feuerrot", "Flame red", "Rouge feu", "Rojo vivo", "Rosso fuoco", "Vuurrood");
		this.addInInventory(inventory, "RAL 3001", 165, 32, 25, "Signalrot", "Signal red", "Rouge de sécurité", "Rojo señales", "Rosso  segnale", "Signaalrood");
		this.addInInventory(inventory, "RAL 3002", 162, 35, 29, "Karminrot", "Carmine red", "Rouge carmin", "Rojo carmin", "Rosso carminio", "Karmijnrood");
		this.addInInventory(inventory, "RAL 3003", 155, 17, 30, "Rubinrot", "Ruby red", "Rouge rubis", "Rojo rubí", "Rosso rubino", "Robijnrood");
		this.addInInventory(inventory, "RAL 3004", 117, 21, 30, "Purpurrot", "Purple red", "Rouge pourpre", "Rojo purpura", "Rosso porpora", "Purperrood");
		this.addInInventory(inventory, "RAL 3005", 94, 33, 41, "Weinrot", "Wine red", "Rouge vin", "Rojo vino", "Rosso vino", "Wijnrood");
		this.addInInventory(inventory, "RAL 3007", 65, 34, 39, "Schwarzrot", "Black red", "Rouge noir", "Rojo negruzco", "Rosso nerastro", "Zwartrood");
		this.addInInventory(inventory, "RAL 3009", 100, 36, 36, "Oxidrot", "Oxide red", "Rouge oxyde", "Rojo óxido", "Rosso  ossido", "Oxyderood");
		this.addInInventory(inventory, "RAL 3011", 120, 31, 25, "Braunrot", "Brown red", "Rouge brun", "Rojo pardo", "Rosso marrone", "Bruinrood");
		this.addInInventory(inventory, "RAL 3012", 193, 135, 107, "Beigerot", "Beige red", "Rouge beige", "Rojo beige", "Rosso beige", "Beigerood");
		this.addInInventory(inventory, "RAL 3013", 161, 35, 18, "Tomatenrot", "Tomato red", "Rouge tomate", "Rojo tomate", "Rosso pomodoro", "Tomaatrood");
		this.addInInventory(inventory, "RAL 3014", 211, 110, 112, "Altrosa", "Antique pink", "Vieux rose", "Rojo viejo", "Rosa antico", "Oudroze");
		this.addInInventory(inventory, "RAL 3015", 234, 137, 154, "Hellrosa", "Light pink", "Rose clair", "Rosa claro", "Rosa chiaro", "Lichtroze");
		this.addInInventory(inventory, "RAL 3016", 179, 40, 33, "Korallenrot", "Coral red", "Rouge corail", "Rojo coral", "Rosso corallo", "Koraalrood");
		this.addInInventory(inventory, "RAL 3017", 230, 50, 68, "Rosé", "Rose", "Rosé", "Rosa", "Rosato", "Bleekrood");
		this.addInInventory(inventory, "RAL 3018", 213, 48, 50, "Erdbeerrot", "Strawberry red", "Rouge fraise", "Rojo fresa", "Rosso fragola", "Aardbeirood");
		this.addInInventory(inventory, "RAL 3020", 204, 6, 5, "Verkehrsrot", "Traffic red", "Rouge signalisation", "Rojo tráfico", "Rosso traffico", "Verkeersrood");
		this.addInInventory(inventory, "RAL 3022", 217, 80, 48, "Lachsrot", "Salmon pink", "Rouge saumon", "Rojo salmón", "Rosso salmone", "Zalmrood");
		this.addInInventory(inventory, "RAL 3024", 248, 0, 0, "Leuchtrot", "Luminous red", "Rouge brillant", "Rojo brillante", "Rosso brillante", "Briljantrood");
		this.addInInventory(inventory, "RAL 3026", 254, 0, 0, "Leuchthellrot", "Luminous bright red", "Rouge clair brillant", "Rojo claro brillante", "Rosso chiaro brillante", "Briljant lichtrood");
		this.addInInventory(inventory, "RAL 3027", 197, 29, 52, "Himbeerrot", "Raspberry red", "Rouge framboise", "Rojo frambuesa", "Rosso lampone", "Framboosrood");
		this.addInInventory(inventory, "RAL 3028", 203, 50, 52, "Reinrot", "Pure  red", "Rouge puro", "Rojo puro", "Rosso puro", "Zuiverrood");
		this.addInInventory(inventory, "RAL 3031", 179, 36, 40, "Orientrot", "Orient red", "Rouge oriental", "Rojo oriente", "Rosso oriente", "Oriëntrood");
		this.addInInventory(inventory, "RAL 3032", 114, 20, 34, "Perlrubinrot", "Pearl ruby red", "Rouge rubis nacré", "Rojo rubí perlado", "Rosso rubino perlato", "Parelmoer-donkerrood");
		this.addInInventory(inventory, "RAL 3033", 180, 76, 67, "Perlrosa", "Pearl pink", "Rose nacré", "Rosa perlado", "Rosa perlato", "Parelmoer-lichtrood");
		this.addInInventory(inventory, "RAL 4001", 222, 76, 138, "Rotlila", "Red lilac", "Lilas rouge", "Rojo lila", "Lilla rossastro", "Roodlila");
		this.addInInventory(inventory, "RAL 4002", 146, 43, 62, "Rotviolett", "Red violet", "Violet rouge", "Rojo violeta", "Viola rossastro", "Roodpaars");
		this.addInInventory(inventory, "RAL 4003", 222, 76, 138, "Erikaviolett", "Heather violet", "Violet bruyère", "Violeta érica", "Viola erica", "Heidepaars");
		this.addInInventory(inventory, "RAL 4004", 110, 28, 52, "Bordeauxviolett", "Claret violet", "Violet bordeaux", "Burdeos", "Viola bordeaux", "Bordeauxpaars");
		this.addInInventory(inventory, "RAL 4005", 108, 70, 117, "Blaulila", "Blue lilac", "Lilas bleu", "Lila azulado", "Lilla bluastro", "Blauwlila");
		this.addInInventory(inventory, "RAL 4006", 160, 52, 114, "Verkehrspurpur", "Traffic purple", "Pourpre signalisation", "Púrpurá tráfico", "Porpora traffico", "Verkeerspurper");
		this.addInInventory(inventory, "RAL 4007", 74, 25, 44, "Purpurviolett", "Purple violet", "Violet pourpre", "Violeta púrpura", "Porpora violetto", "Purperviolet");
		this.addInInventory(inventory, "RAL 4008", 144, 70, 132, "Signalviolett", "Signal violet", "Violet de sécurité", "Violeta señales", "Violetto segnale", "Signaalviolet");
		this.addInInventory(inventory, "RAL 4009", 164, 125, 144, "Pastellviolett", "Pastel violet", "Violet pastel", "Violeta pastel", "Violetto pastello", "Pastelviolet");
		this.addInInventory(inventory, "RAL 4010", 215, 45, 109, "Telemagenta", "Telemagenta", "Telemagenta", "Magenta tele", "Tele Magenta", "Telemagenta");
		this.addInInventory(inventory, "RAL 4011", 134, 115, 161, "Perlviolett", "Pearl violet", "Violet nacré", "Violeta perlado", "Violetto perlato", "Parelmoer-donkerviolet");
		this.addInInventory(inventory, "RAL 4012", 108, 104, 129, "Perlbrombeer", "Pearl black berry", "Mûre nacré", "Morado perlado", "Mora perlato", "Parelmoer-lichtviolet");
		this.addInInventory(inventory, "RAL 5000", 42, 46, 75, "Violettblau", "Violet blue", "Bleu violet", "Azul violeta", "Blu violaceo", "Paarsblauw");
		this.addInInventory(inventory, "RAL 5001", 31, 52, 56, "Grünblau", "Green blue", "Bleu vert", "Azul verdoso", "Blu verdastro", "Groenblauw");
		this.addInInventory(inventory, "RAL 5002", 32, 33, 79, "Ultramarinblau", "Ultramarine blue", "Bleu outremer", "Azul ultramar", "Blu oltremare", "Ultramarijnblauw");
		this.addInInventory(inventory, "RAL 5003", 29, 30, 51, "Saphirblau", "Saphire blue", "Bleu saphir", "Azul zafiro", "Blu zaffiro", "Saffierblauw");
		this.addInInventory(inventory, "RAL 5004", 32, 33, 79, "Schwarzblau", "Black blue", "Bleu noir", "Azul negruzco", "Blu nerastro", "Zwartblauw");
		this.addInInventory(inventory, "RAL 5005", 30, 45, 110, "Signalblau", "Signal blue", "Bleu de sécurité", "Azul señales", "Blu segnale", "Signaalblauw");
		this.addInInventory(inventory, "RAL 5007", 62, 95, 138, "Brillantblau", "Brillant blue", "Bleu brillant", "Azul brillante", "Blu brillante", "Briljantblauw");
		this.addInInventory(inventory, "RAL 5008", 38, 37, 45, "Graublau", "Grey blue", "Bleu gris", "Azul grisáceo", "Blu grigiastro", "Grijsblauw");
		this.addInInventory(inventory, "RAL 5009", 2, 86, 105, "Azurblau", "Azure blue", "Bleu azur", "Azul azur", "Blu  azzurro", "Azuurblauw");
		this.addInInventory(inventory, "RAL 5010", 14, 41, 75, "Enzianblau", "Gentian blue", "Bleu gentiane", "Azul genciana", "Blu  genziana", "Gentiaanblauw");
		this.addInInventory(inventory, "RAL 5011", 35, 26, 36, "Stahlblau", "Steel blue", "Bleu acier", "Azul acero", "Blu acciaio", "Staalblauw");
		this.addInInventory(inventory, "RAL 5012", 59, 131, 189, "Lichtblau", "Light blue", "Bleu clair", "Azul luminoso", "Blu luce", "Lichtblauw");
		this.addInInventory(inventory, "RAL 5013", 37, 41, 74, "Kobaltblau", "Cobalt blue", "Bleu cobalt", "Azul cobalto", "Blu cobalto", "Kobaltblauw");
		this.addInInventory(inventory, "RAL 5014", 96, 111, 140, "Taubenblau", "Pigeon blue", "Bleu pigeon", "Azul olombino", "Blu colomba", "Duifblauw");
		this.addInInventory(inventory, "RAL 5015", 34, 113, 179, "Himmelblau", "Sky blue", "Bleu ciel", "Azul celeste", "Blu cielo", "Hemelsblauw");
		this.addInInventory(inventory, "RAL 5017", 6, 57, 113, "Verkehrsblau", "Traffic blue", "Bleu signalisation", "Azul tráfico", "Blu traffico", "Verkeersblauw");
		this.addInInventory(inventory, "RAL 5018", 63, 136, 143, "Türkisblau", "Turquoise blue", "Bleu turquoise", "Azul turquesa", "Blu turchese", "Turkooisblauw");
		this.addInInventory(inventory, "RAL 5019", 27, 85, 131, "Capriblau", "Capri blue", "Bleu capri", "Azul capri", "Blu capri", "Capriblauw");
		this.addInInventory(inventory, "RAL 5020", 29, 51, 74, "Ozeanblau", "Ocean blue", "Bleu océan", "Azul oceano", "Blu oceano", "Oceaanblauw");
		this.addInInventory(inventory, "RAL 5021", 37, 109, 123, "Wasserblau", "Water blue", "Bleu d’eau", "Azul agua", "Blu acqua", "Waterblauw");
		this.addInInventory(inventory, "RAL 5022", 37, 40, 80, "Nachtblau", "Night blue", "Bleu nocturne", "Azul noche", "Blu notte", "Nachtblauw");
		this.addInInventory(inventory, "RAL 5023", 73, 103, 141, "Fernblau", "Distant blue", "Bleu distant", "Azul lejanía", "Blu distante", "Verblauw");
		this.addInInventory(inventory, "RAL 5024", 93, 155, 155, "Pastellblau", "Pastel blue", "Bleu pastel", "Azul pastel", "Blu pastello", "Pastelblauw");
		this.addInInventory(inventory, "RAL 5025", 42, 100, 120, "Perlenzian", "Pearl gentian blue", "Gentiane nacré", "Gencian perlado", "Blu genziana perlato", "Parelmoerblauw");
		this.addInInventory(inventory, "RAL 5026", 16, 44, 84, "Perlnachtblau", "Pearl night blue", "Bleu nuit nacré", "Azul noche perlado", "Blu notte perlato", "Parelmoer-nachtblauw");
		this.addInInventory(inventory, "RAL 6000", 49, 102, 80, "Patinagrün", "Patina green", "Vert patine", "Verde patina", "Verde patina", "Patinagroen");
		this.addInInventory(inventory, "RAL 6001", 40, 114, 51, "Smaragdgrün", "Emerald green", "Vert émeraude", "Verde esmeralda", "Verde smeraldo", "Smaragdgroen");
		this.addInInventory(inventory, "RAL 6002", 45, 87, 44, "Laubgrün", "Leaf green", "Vert feuillage", "Verde hoja", "Verde foglia", "Loofgroen");
		this.addInInventory(inventory, "RAL 6003", 66, 70, 50, "Olivgrün", "Olive green", "Vert olive", "Verde oliva", "Verde oliva", "Olijfgroen");
		this.addInInventory(inventory, "RAL 6004", 31, 58, 61, "Blaugrün", "Blue green", "Vert bleu", "Verde azulado", "Verde bluastro", "Blauwgroen");
		this.addInInventory(inventory, "RAL 6005", 47, 69, 56, "Moosgrün", "Moss green", "Vert mousse", "Verde musgo", "Verde muschio", "Mosgroen");
		this.addInInventory(inventory, "RAL 6006", 62, 59, 50, "Grauoliv", "Grey olive", "Olive gris", "Oliva grisáceo", "Oliva grigiastro", "Grijs olijfgroen");
		this.addInInventory(inventory, "RAL 6007", 52, 59, 41, "Flaschengrün", "Bottle green", "Vert bouteille", "Verde botella", "Verde bottiglia", "Flessegroen");
		this.addInInventory(inventory, "RAL 6008", 57, 53, 42, "Braungrün", "Brown green", "Vert brun", "Verde parduzco", "Verde brunastro", "Bruingroen");
		this.addInInventory(inventory, "RAL 6009", 49, 55, 43, "Tannengrün", "Fir green", "Vert sapin", "Verde abeto", "Verde abete", "Dennegroen");
		this.addInInventory(inventory, "RAL 6010", 53, 104, 45, "Grasgrün", "Grass green", "Vert herbe", "Verde hierba", "Verde erba", "Grasgroen");
		this.addInInventory(inventory, "RAL 6011", 88, 114, 70, "Resedagrün", "Reseda green", "Vert réséda", "Verde reseda", "Verde reseda", "Resedagroen");
		this.addInInventory(inventory, "RAL 6012", 52, 62, 64, "Schwarzgrün", "Black green", "Vert noir", "Verde negruzco", "Verde nerastro", "Zwartgroen");
		this.addInInventory(inventory, "RAL 6013", 108, 113, 86, "Schilfgrün", "Reed green", "Vert jonc", "Verde caña", "Verde canna", "Rietgroen");
		this.addInInventory(inventory, "RAL 6014", 71, 64, 46, "Gelboliv", "Yellow olive", "Olive jaune", "Amarillo oliva", "Oliva giallastro", "Geel olijfgroen");
		this.addInInventory(inventory, "RAL 6015", 59, 60, 54, "Schwarzoliv", "Black olive", "Olive noir", "Oliva negruzco", "Oliva nerastro", "Zwart olijfgroen");
		this.addInInventory(inventory, "RAL 6016", 30, 89, 69, "Türkisgrün", "Turquoise green", "Vert turquoise", "Verde turquesa", "Verde turchese", "Turkooisgroen");
		this.addInInventory(inventory, "RAL 6017", 76, 145, 65, "Maigrün", "May green", "Vert mai", "Verde mayo", "Verde maggio", "Meigroen");
		this.addInInventory(inventory, "RAL 6018", 87, 166, 57, "Gelbgrün", "Yellow green", "Vert jaune", "Verde amarillento", "Verde giallastro", "Geelgroen");
		this.addInInventory(inventory, "RAL 6019", 189, 236, 182, "Weißgrün", "Pastel green", "Vert blanc", "Verde lanquecino", "Verde biancastro", "Witgroen");
		this.addInInventory(inventory, "RAL 6020", 46, 58, 35, "Chromoxidgrün", "Chrome green", "Vert oxyde chromique", "Verde cromo", "Verde cromo", "Chroom-oxydegroen");
		this.addInInventory(inventory, "RAL 6021", 137, 172, 118, "Blassgrün", "Pale green", "Vert pâle", "Verde pálido", "Verde pallido", "Bleekgroen");
		this.addInInventory(inventory, "RAL 6022", 37, 34, 27, "Braunoliv", "Olive drab", "Olive brun", "Oliva parduzco", "Oliva brunastro", "Bruin olijfgroen");
		this.addInInventory(inventory, "RAL 6024", 48, 132, 70, "Verkehrsgrün", "Traffic green", "Vert signalisation", "Verde tráfico", "Verde traffico", "Verkeersgroen");
		this.addInInventory(inventory, "RAL 6025", 61, 100, 45, "Farngrün", "Fern green", "Vert fougère", "Verde helecho", "Verde felce", "Varengroen");
		this.addInInventory(inventory, "RAL 6026", 1, 93, 82, "Opalgrün", "Opal green", "Vert opale", "Verde opalo", "Verde opale", "Opaalgroen");
		this.addInInventory(inventory, "RAL 6027", 132, 195, 190, "Lichtgrün", "Light green", "Vert clair", "Verde luminoso", "Verde chiaro", "Lichtgroen");
		this.addInInventory(inventory, "RAL 6028", 44, 85, 69, "Kieferngrün", "Pine green", "Vert pin", "Verde pino", "Verde pino", "Pijnboomgroen");
		this.addInInventory(inventory, "RAL 6029", 32, 96, 61, "Minzgrün", "Mint green", "Vert menthe", "Verde menta", "Verde menta", "Mintgroen");
		this.addInInventory(inventory, "RAL 6032", 49, 127, 67, "Signalgrün", "Signal green", "Vert de sécurité", "Verde señales", "Verde segnale", "Signaalgroen");
		this.addInInventory(inventory, "RAL 6033", 73, 126, 118, "Minttürkis", "Mint turquoise", "Turquoise menthe", "Turquesa menta", "Turchese menta", "Mintturquoise");
		this.addInInventory(inventory, "RAL 6034", 127, 181, 181, "Pastelltürkis", "Pastel turquoise", "Turquoise pastel", "Turquesa pastel", "Turchese pastello", "Pastelturquoise");
		this.addInInventory(inventory, "RAL 6035", 28, 84, 45, "Perlgrün", "Pearl green", "Vert nacré", "Verde perlado", "Verde perlato", "Parelmoer-donkergroen");
		this.addInInventory(inventory, "RAL 6036", 22, 53, 55, "Perlopalgrün", "Pearl opal green", "Vert opal nacré", "Verde ópalo perlado", "Verde opalo perlato", "Parelmoer-lichtgroen");
		this.addInInventory(inventory, "RAL 6037", 0, 143, 57, "Reingrün", "Pure green", "Vert pur", "Verde puro", "Verde puro", "Zuivergroen");
		this.addInInventory(inventory, "RAL 6038", 0, 187, 45, "Leuchtgrün", "Luminous green", "Vert brillant", "Verde brillante", "Verde brillante", "Briljantgroen");
		this.addInInventory(inventory, "RAL 7000", 120, 133, 139, "Fehgrau", "Squirrel grey", "Gris petit-gris", "Gris ardilla", "Grigio vaio", "Pelsgrijs");
		this.addInInventory(inventory, "RAL 7001", 138, 149, 151, "Silbergrau", "Silver grey", "Gris argent", "Gris plata", "Grigio argento", "Zilvergrijs");
		this.addInInventory(inventory, "RAL 7002", 126, 123, 82, "Olivgrau", "Olive grey", "Gris olive", "Gris oliva", "Grigio olivastro", "Olijfgrijs");
		this.addInInventory(inventory, "RAL 7003", 108, 112, 89, "Moosgrau", "Moss grey", "Gris mousse", "Gris musgo", "Grigio muschio", "Mosgrijs");
		this.addInInventory(inventory, "RAL 7004", 150, 153, 146, "Signalgrau", "Signal grey", "Gris de sécurité", "Gris señales", "Grigio segnale", "Signaalgrijs");
		this.addInInventory(inventory, "RAL 7005", 100, 107, 99, "Mausgrau", "Mouse grey", "Gris souris", "Gris ratón", "Grigio topo", "Muisgrijs");
		this.addInInventory(inventory, "RAL 7006", 109, 101, 82, "Beigegrau", "Beige grey", "Gris beige", "Gris beige", "Grigio beige", "Beigegrijs");
		this.addInInventory(inventory, "RAL 7008", 106, 95, 49, "Khakigrau", "Khaki grey", "Gris kaki", "Gris caqui", "Grigio kaki", "Kakigrijs");
		this.addInInventory(inventory, "RAL 7009", 77, 86, 69, "Grüngrau", "Green grey", "Gris vert", "Gris verdoso", "Grigio verdastro", "Groengrijs");
		this.addInInventory(inventory, "RAL 7010", 76, 81, 74, "Zeltgrau", "Tarpaulin grey", "Gris tente", "Gris lona", "Grigio tenda", "Zeildoekgrijs");
		this.addInInventory(inventory, "RAL 7011", 67, 75, 77, "Eisengrau", "Iron grey", "Gris fer", "Gris hierro", "Grigio ferro", "IJzergrijs");
		this.addInInventory(inventory, "RAL 7012", 78, 87, 84, "Basaltgrau", "Basalt grey", "Gris basalte", "Gris basalto", "Grigio basalto", "Bazaltgrijs");
		this.addInInventory(inventory, "RAL 7013", 70, 69, 49, "Braungrau", "Brown grey", "Gris brun", "Gris parduzco", "Grigio brunastro", "Bruingrijs");
		this.addInInventory(inventory, "RAL 7015", 67, 71, 80, "Schiefergrau", "Slate grey", "Gris ardoise", "Gris pizarra", "Grigio ardesia", "Leigrijs");
		this.addInInventory(inventory, "RAL 7016", 41, 49, 51, "Anthrazitgrau", "Anthracite grey", "Gris anthracite", "Gris antracita", "Grigio antracite", "Antracietgrijs");
		this.addInInventory(inventory, "RAL 7021", 35, 40, 43, "Schwarzgrau", "Black grey", "Gris noir", "Gris negruzco", "Grigio nerastro", "Zwartgrijs");
		this.addInInventory(inventory, "RAL 7022", 51, 47, 44, "Umbragrau", "Umbra grey", "Gris terre d’ombre", "Gris sombra", "Grigio ombra", "Ombergrijs");
		this.addInInventory(inventory, "RAL 7023", 104, 108, 94, "Betongrau", "Concrete grey", "Gris béton", "Gris hormigón", "Grigio calcestruzzo", "Betongrijs");
		this.addInInventory(inventory, "RAL 7024", 71, 74, 81, "Graphitgrau", "Graphite grey", "Gris graphite", "Gris grafita", "Grigio grafite", "Grafietgrijs");
		this.addInInventory(inventory, "RAL 7026", 47, 53, 59, "Granitgrau", "Granite grey", "Gris granit", "Gris granito", "Grigio granito", "Granietgrijs");
		this.addInInventory(inventory, "RAL 7030", 139, 140, 122, "Steingrau", "Stone grey", "Gris pierre", "Gris piedra", "Grigio pietra", "Steengrijs");
		this.addInInventory(inventory, "RAL 7031", 71, 75, 78, "Blaugrau", "Blue grey", "Gris bleu", "Gris azulado", "Grigio bluastro", "Blauwgrijs");
		this.addInInventory(inventory, "RAL 7032", 184, 183, 153, "Kieselgrau", "Pebble grey", "Gris silex", "Gris guijarro", "Grigio ghiaia", "Kiezelgrijs");
		this.addInInventory(inventory, "RAL 7033", 125, 132, 113, "Zementgrau", "Cement grey", "Gris ciment", "Gris cemento", "Grigio cemento", "Cementgrijs");
		this.addInInventory(inventory, "RAL 7034", 143, 139, 102, "Gelbgrau", "Yellow grey", "Gris jaune", "Gris amarillento", "Grigio giallastro", "Geelgrijs");
		this.addInInventory(inventory, "RAL 7035", 215, 215, 215, "Lichtgrau", "Light grey", "Gris clair", "Gris luminoso", "Grigio luce", "Lichtgrijs");
		this.addInInventory(inventory, "RAL 7036", 127, 118, 121, "Platingrau", "Platinum grey", "Gris platine", "Gris platino", "Grigio platino", "Platinagrijs");
		this.addInInventory(inventory, "RAL 7037", 125, 127, 120, "Staubgrau", "Dusty grey", "Gris poussière", "Gris polvo", "Grigio polvere", "Stofgrijs");
		this.addInInventory(inventory, "RAL 7038", 195, 195, 195, "Achatgrau", "Agate grey", "Gris agate", "Gris ágata", "Grigio agata", "Agaatgrijs");
		this.addInInventory(inventory, "RAL 7039", 108, 105, 96, "Quarzgrau", "Quartz grey", "Gris quartz", "Gris cuarzo", "Grigio quarzo", "Kwartsgrijs");
		this.addInInventory(inventory, "RAL 7040", 157, 161, 170, "Fenstergrau", "Window grey", "Gris fenêtre", "Gris ventana", "Grigio finestra", "Venstergrijs");
		this.addInInventory(inventory, "RAL 7042", 141, 148, 141, "Verkehrsgrau A", "Traffic grey A", "Gris signalisation A", "Gris tráfico A", "Grigio traffico A", "Verkeesgrijs A");
		this.addInInventory(inventory, "RAL 7043", 78, 84, 82, "Verkehrsgrau B", "Traffic grey B", "Gris signalisation B", "Gris tráfico B", "Grigio traffico B", "Verkeersgrijs B");
		this.addInInventory(inventory, "RAL 7044", 202, 196, 176, "Seidengrau", "Silk grey", "Gris soie", "Gris seda", "Grigio seta", "Zijdegrijs");
		this.addInInventory(inventory, "RAL 7045", 144, 144, 144, "Telegrau 1", "Telegrey 1", "Telegris 1", "Gris tele 1", "Tele grigio 1", "Telegrijs 1");
		this.addInInventory(inventory, "RAL 7046", 130, 137, 143, "Telegrau 2", "Telegrey 2", "Telegris 2", "Gris tele 2", "Tele grigio 2", "Telegrijs 2");
		this.addInInventory(inventory, "RAL 7047", 208, 208, 208, "Telegrau 4", "Telegrey 4", "Telegris 4", "Gris tele 4", "Tele grigio 4", "Telegrijs 4");
		this.addInInventory(inventory, "RAL 7048", 137, 129, 118, "Perlmausgrau", "Pearl mouse grey", "Gris souris nacré", "Gris musgo perlado", "Grigio topo perlato", "Parelmoer-muisgrijs");
		this.addInInventory(inventory, "RAL 8000", 130, 108, 52, "Grünbraun", "Green brown", "Brun vert", "Pardo verdoso", "Marrone verdastro", "Groenbruin");
		this.addInInventory(inventory, "RAL 8001", 149, 95, 32, "Ockerbraun", "Ochre brown", "Brun terre de Sienne", "Pardo ocre", "Marrone ocra", "Okerbruin");
		this.addInInventory(inventory, "RAL 8002", 108, 59, 42, "Signalbraun", "Signal brown", "Brun de sécurité", "Marrón señales", "Marrone segnale", "Signaalbruin");
		this.addInInventory(inventory, "RAL 8003", 115, 66, 34, "Lehmbraun", "Clay brown", "Brun argile", "Pardo arcilla", "Marrone fango", "Leembruin");
		this.addInInventory(inventory, "RAL 8004", 142, 64, 42, "Kupferbraun", "Copper brown", "Brun cuivré", "Pardo cobre", "Marrone rame", "Koperbruin");
		this.addInInventory(inventory, "RAL 8007", 89, 53, 31, "Rehbraun", "Fawn brown", "Brun fauve", "Pardo corzo", "Marrone capriolo", "Reebruin");
		this.addInInventory(inventory, "RAL 8008", 111, 79, 40, "Olivbraun", "Olive brown", "Brun olive", "Pardo oliva", "Marrone oliva", "Olijfbruin");
		this.addInInventory(inventory, "RAL 8011", 91, 58, 41, "Nussbraun", "Nut brown", "Brun noisette", "Pardo nuez", "Marrone noce", "Notebruin");
		this.addInInventory(inventory, "RAL 8012", 89, 35, 33, "Rotbraun", "Red brown", "Brun rouge", "Pardo rojo", "Marrone rossiccio", "Roodbruin");
		this.addInInventory(inventory, "RAL 8014", 56, 44, 30, "Sepiabraun", "Sepia brown", "Brun sépia", "Sepia", "Marrone seppia", "Sepiabruin");
		this.addInInventory(inventory, "RAL 8015", 99, 58, 52, "Kastanienbraun", "Chestnut brown", "Marron", "Castaño", "Marrone castagna", "Kastanjebruin");
		this.addInInventory(inventory, "RAL 8016", 76, 47, 39, "Mahagonibraun", "Mahogany brown", "Brun acajou", "Caoba", "Marrone mogano", "Mahoniebruin");
		this.addInInventory(inventory, "RAL 8017", 69, 50, 46, "Schokoladen-braun", "Chocolate brown", "Brun chocolat", "Chocolate", "Marrone cioccolata", "Chocoladebruin");
		this.addInInventory(inventory, "RAL 8019", 64, 58, 58, "Graubraun", "Grey brown", "Brun gris", "Pardo grisáceo", "Marrone grigiastro", "Grijsbruin");
		this.addInInventory(inventory, "RAL 8022", 33, 33, 33, "Schwarzbraun", "Black brown", "Brun noir", "Pardo negruzco", "Marrone nerastro", "Zwartbruin");
		this.addInInventory(inventory, "RAL 8023", 166, 94, 46, "Orangebraun", "Orange brown", "Brun orangé", "Pardo anaranjado", "Marrone arancio", "Oranjebruin");
		this.addInInventory(inventory, "RAL 8024", 121, 85, 61, "Beigebraun", "Beige brown", "Brun beige", "Pardo beige", "Marrone beige", "Beigebruin");
		this.addInInventory(inventory, "RAL 8025", 117, 92, 72, "Blassbraun", "Pale brown", "Brun pâle", "Pardo pálido", "Marrone pallido", "Bleekbruin");
		this.addInInventory(inventory, "RAL 8028", 78, 59, 49, "Terrabraun", "Terra brown", "Brun terre", "Marrón tierra", "Marrone terra", "Terrabruin");
		this.addInInventory(inventory, "RAL 8029", 118, 60, 40, "Perlkupfer", "Pearl copper", "Cuivre nacré", "Cobre perlado", "Rame perlato", "Parelmoerkoper");
		this.addInInventory(inventory, "RAL 9001", 250, 244, 227, "Cremeweiß", "Cream", "Blanc crème", "Blanco crema", "Bianco crema", "Crèmewit");
		this.addInInventory(inventory, "RAL 9002", 231, 235, 218, "Grauweiß", "Grey white", "Blanc gris", "Blanco grisáceo", "Bianco grigiastro", "Grijswit");
		this.addInInventory(inventory, "RAL 9003", 244, 244, 244, "Signalweiß", "Signal white", "Blanc de sécurité", "Blanco señales", "Bianco segnale", "Signaalwit");
		this.addInInventory(inventory, "RAL 9004", 40, 40, 40, "Signalschwarz", "Signal black", "Noir de sécurité", "Negro señales", "Nero segnale", "Signaalzwart");
		this.addInInventory(inventory, "RAL 9005", 10, 10, 13, "Tiefschwarz", "Jet black", "Noir foncé", "Negro intenso", "Nero intenso", "Gitzwart");
		this.addInInventory(inventory, "RAL 9006", 165, 165, 165, "Weißaluminium", "White aluminium", "Aluminium blanc", "Aluminio blanco", "Aluminio brillante", "Blank aluminiumkleurig");
		this.addInInventory(inventory, "RAL 9007", 143, 143, 143, "Graualuminium", "Grey aluminium", "Aluminium gris", "Aluminio gris", "Aluminio grigiastro", "Grijs aluminiumkleurig");
		this.addInInventory(inventory, "RAL 9010", 255, 255, 255, "Reinweiß", "Pure white", "Blanc pur", "Blanco puro", "Bianco puro", "Zuiverwit");
		this.addInInventory(inventory, "RAL 9011", 28, 28, 28, "Graphitschwarz", "Graphite black", "Noir graphite", "Negro grafito", "Nero grafite", "Grafietzwart");
		this.addInInventory(inventory, "RAL 9016", 246, 246, 246, "Verkehrsweiß", "Traffic white", "Blanc signalisation", "Blanco tráfico", "Bianco traffico", "Verkeerswit");
		this.addInInventory(inventory, "RAL 9017", 30, 30, 30, "Verkehrs-schwarz", "Traffic black", "Noir signalisation", "Negro tráfico", "Nero traffico", "Verkeerszwart");
		this.addInInventory(inventory, "RAL 9018", 215, 215, 215, "Papyrusweiß", "Papyrus white", "Blanc papyrus", "Blanco papiro", "Bianco papiro", "Papyruswit");
		this.addInInventory(inventory, "RAL 9022", 156, 156, 156, "Perlhellgrau", "Pearl light grey", "Gris clair nacré", "Gris claro perlado", "Grigio chiaro perlato", "Parelmoer-lichtgrijs");
		this.addInInventory(inventory, "RAL 9023", 130, 130, 130, "Perldunkelgrau", "Pearl dark grey", "Gris fonçé nacré", "Gris oscuro perlado", "Grigio scuro perlato", "Parelmoer-donkergrijs");

	}

	public abstract void addInInventory(
			LabeledColorInventory inventory,
			String code,
			int red, int green, int blue,
			String germanName, String englishName, String frenchName, String spanishName, String italianName, String nederlandsName);

}
